nginx:
  image: nginx:1.10.1
  volumes:
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    - ./var/nginx-log/:/var/log/nginx
  volumes_from:
    - php
  links:
    - php:php
  ports:
    - 80
  environment:
    SERVICE_80_NAME: website
    SERVICE_TAGS: production

php:
  build: ./docker/php
  volumes:
    - ./:/var/www/html/
  environment:
    SERVICE_URL_ORDER_BACKEND: lbbackend.service.consul:8081/backend-service/order/
    SERVICE_URL_INVENTORY_BACKEND: lbbackend.service.consul:8081/backend-service/inventory/
  dns:
    - 172.17.0.1 # consul
    - 8.8.8.8
