consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

registrator:
  command: -ip=192.168.99.100 consul://consul:8500
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

# Frontend load balancer and discovery
lb:
  build: ./lb
  links:
    - consul
  ports:
    - "80:80"
  environment:
    CONSUL_URL: consul:8500
  volumes:
    - ./lb/consul-template:/etc/consul-template

# Backend Discovery service
discovery:
  build: ./discovery
  links:
    - consul
  ports:
    - "8081:8081" # This port should not be open to the public internet
  environment:
    CONSUL_URL: consul:8500
  volumes:
    - ./discovery/consul-template:/etc/consul-template
